### ISSUE TITLE
Any development?

### ISSUE THREAD

**Issue by acuifex** [sstokic-tgm/Gladiatorcheatz-v2.1-Linux#2]
i'm really bored from using aimtux forks

**Comment by sstokic-tgm** [comment]
I'm in the last time really stressed with my work that I don't find any time to continue contributing on this project.
I will try to find some time / start working on it again!

**Comment by acuifex** [comment]
okay. thank you for your work!

**Comment by acuifex** [comment]
... I still wait and hope for linux version C:

**Comment by acuifex** [comment]
Big F for this cheat :c
